from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.security import OAuth2PasswordRequestForm

from api.schemas import UserActivate, UserResponse, TokenResponse
from api.dependencies import get_user_repo
from api.auth import (
    verify_password, get_password_hash, create_access_token, get_current_user
)
from api.database import User

router = APIRouter(prefix="/auth", tags=["Authentication"])

@router.post("/login", response_model=TokenResponse)
async def login(
    form_data: OAuth2PasswordRequestForm = Depends(),
    user_repo = Depends(get_user_repo)
):
    """
    Log in using username/email and password.
    Supports form-data input for native Swagger UI OAuth2 workflow compatibility.
    """
    user = await user_repo.get_by_username_or_email(form_data.username)
    if not user or not user.hashed_password:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Incorrect username/email or password"
        )
    
    if not verify_password(form_data.password, user.hashed_password):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Incorrect username/email or password"
        )
        
    if not user.is_active:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="User account is inactive. Please activate your account first."
        )

    # Standard sub claim maps to username
    access_token = create_access_token(data={"sub": user.username})
    return {"access_token": access_token, "token_type": "bearer"}

@router.post("/activate", response_model=UserResponse)
async def activate(
    payload: UserActivate,
    user_repo = Depends(get_user_repo)
):
    """
    Activate a pending user profile and establish their login password.
    Requires a valid onboarding token generated by a supervisor.
    """
    user = await user_repo.get_by_activation_token(payload.token)
    if not user:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid or expired activation token"
        )
        
    hashed_password = get_password_hash(payload.password)
    activated_user = await user_repo.activate_user(user, hashed_password)
    return activated_user

@router.get("/me", response_model=UserResponse)
async def me(current_user: User = Depends(get_current_user)):
    """
    Get profile information for the currently authenticated user.
    """
    return current_user
